### ISSUE TITLE
Desain Projek

### ISSUE THREAD

**Issue by haniftio** [haniftio/Sensor_Peringatan_Gempa_Bumi#2]

**Comment by haniftio** [comment]
![Image](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168505785/9e352911-6eca-457b-bd56-c7ceaacf8c2d)
![Image](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168505785/848e5323-42fd-4a85-a7e9-1513a0e60dd4)
![Image](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168505785/adda7a39-f39c-4c9a-af9f-fb0be9fe7e32)
![Image](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168505785/151b5c35-d7d9-4891-847c-5ec2d79955bd)
![Image](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168505785/239ddca6-d386-4b4c-a38a-f62108050560)
![Image](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168505785/57dd7696-88fc-454d-9624-ecf335fb2394)

**Comment by MDavaWardana** [comment]
![Gambar1](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168980365/af37c904-a576-46e4-aa52-9ccb3e7f310b)
![Gambar2](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168980365/13a77ad2-4407-45b9-a550-720ab7ae6645)
![Gambar3](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168980365/27cf8ef2-b2db-4984-9890-8a5b82389470)
![Gambar4](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168980365/15720897-38a8-4007-a7d2-a441e157e874)
![Gambar5](https://github.com/haniftio/Sensor_Peringatan_Gempa_Bumi/assets/168980365/cbb749f7-1e51-4b30-94ac-c4009cb50c6e)
